[package]
name = "spacermake"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
base64 = "0.22.1"
chrono = "0.4.44"
csv = "1.4.0"
dirs = "6.0.0"
extend = "1.2.0"
futures = "0.3.32"
itertools = "0.14"
log = { version = "0.4.31", features = ["kv"] }
maud = "0.27"
parking_lot = "0.12.5"
rumqttc = "0.24.0" # 0.25 requires cmake
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
strum = { version = "0.28.0", features = ["derive"] }
tap = "1.0.1"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "fs", "sync"] }
toml = "1.1.2"
warp = { version = "0.4.3", features = ["server"] }
