[package]
name = "spacermake"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
dirs = "6.0.0"
extend = "1.2.0"
futures = "0.3.33"
itertools = "0.15.0"
log = { version = "0.4.33", features = ["kv"] }
maud = "0.27.0"
md5 = "0.8.1"
reqwest = { version = "0.13.4", features = ["json"] }
rumqttc = "0.24.0" # 0.25 requires cmake
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
strum = { version = "0.28.0", features = ["derive"] }
tap = "1.0.1"
thiserror = "2.0.20"
tokio = { version = "1.53.1", default-features = false, features = ["rt-multi-thread", "macros"] }
toml = "1.1.4"
warp = { version = "0.4.3", features = ["server"] }
chrono = "0.4.45"
csv = "1.4.0"
serde_with = "3.22.0"
urlencoding = "2.1.3"
